"""
file with constants
"""
from arcade import color

# window contants
WINDOW_WIDTH=1280
WINDOW_HEIGHT=720
WINDOW_TITLE = "Lotti Karrotti"

# cells constants
CELL_SPACE=20
CELLS_FIELD_WIDTH=WINDOW_WIDTH*3//4
CELL_CNT=26
CELL_DANGEROUS=(3,6,9, 12, 15, 18, 20, 22, 24)
CELL_RADIUS=50

# players
PLAYER_CNT=2
PLAYER_CNT_MAX=4
PLAYER_CNT_MIN=1
PLAYER_HARE_CNT=2
PLAYER_PROPS=[{"color": "blau"}, {"color": "lila"}]

# boundaries
BOUNDARY_LINE_WIDTH=5
BOUNDARY_LINE_COLOR=color.BABY_BLUE

# players text
TEXT_SPACE=10
TEXT_X_OFFSET=BOUNDARY_LINE_WIDTH+5
TEXT_Y_OFFSET=BOUNDARY_LINE_WIDTH+5
TEXT_SIZE=22
TEXT_FONT_SIZE=(TEXT_SIZE*3)//4

# hares
HARE_WIDTH_ORIG=256
HARE_HEIGHT_ORIG=341
HARE_SPACE=5

# tests
TEST_POS=[(0,16, 24), (3, 9, 17)]

# game
GAME_STATUS_SPRITE_HEIGHT=60
